#!/usr/bin/env python

model_config = {
	        "n_epochs": 100,
	        "batch_size": 12,
                "save_top_k": 1,
                "seed": 42,
                "class_weight": 1.,
                "n_classes": 1,
                "gpu_device": [0],
                "lightning_module": 'CNN_GNN',
                "model_name": 'GatedGCN',
                "extractor_name": 'resnet50',
                "dataset_name": 'UTSW',
                "preset_folds": True,
                "preset_fold_file": 'preset_folds_malignancy_liyuan_091024.pkl',
                "alternate_splitting": False,
                "pretrain": False,
                "freeze_extractor": False,
                "with_edge_attr": False,
                "cross_val": True,
                "nested_cross_val": False,
                "edge_dim": None,
                "use_clinical": False, 
                "n_clinical": 5,
                "region": 'ROI',
                "extractor_channels": 2048,
                "n_in_channels": 2,
                "n_hidden_channels": 64,
                "gnn_out_channels": 8,
                "ag_alpha": 0.25,
	        "dropout": 0.0,
                "l2_reg": 0,
                "learning_rate": 1e-4,
                "lr_sched": True,
                "lr_factor": 0.5,
                "lr_patience": 10,
                "lr_mode": 'max',
                "log_dir": None,
                "transfer": None,
                "n_rotations": 5,
                "balance_classes": False,
               "num_deep_layers": 28,
               "data_path": '../../data/ln_malignancy',
               "primary_dir": 'Processed_Data',
               "transfer_weights_file": 'extracted_weights.pkl',
               "patch_dir": 'Extracted_Patches_v2',
               "fold_dir": 'liyuan_folds',
               "edge_file": 'proto_graphs_092524.pkl',
               "patient_feature_file": 'features_and_labels_092524.pkl',
               "data_version": 'v1',
               "weight_dir": './logs/training_chosen_split_no_graph_lncnn_noedgedim_no_pretrain_nofreeze_copy_attempt_ch2_class2_dp2_weight1_10rot_balance_feat256_nested_clinical_v15',
               "extractor_weight_files": [
                                          'top_models_fold_0/model_epoch=50_val_loss=0.84_val_auc=0.98_val_m=0.93.ckpt',
                                          'top_models_fold_1/model_epoch=21_val_loss=0.76_val_auc=0.98_val_m=0.93.ckpt',
                                          'top_models_fold_2/model_epoch=50_val_loss=0.56_val_auc=0.98_val_m=0.95.ckpt',
                                          'top_models_fold_3/model_epoch=80_val_loss=0.91_val_auc=0.96_val_m=0.91.ckpt',
                                          'top_models_fold_4/model_epoch=24_val_loss=0.77_val_auc=0.98_val_m=0.94.ckpt',
                                         ],
               }         

