#!/usr/bin/env python

model_config = {
	        "n_epochs": 100,
	        "batch_size": 12,
                "seed": 42,
                "n_classes": 1,
                "model_name": 'GatedGCN',
                "extractor_name": 'LNCNN',
                "dataset_name": 'UTSW',
                "preset_folds": False,
                "preset_fold_file": 'preset_folds_malignancy.pkl',
                "with_edge_attr": False,
                "cross_val": True,
                "nested_cross_val": False,
                "edge_dim": None,
                "use_clinical": False, 
                "n_clinical": 0,
                "n_in_channels": 1,
                "n_extracted_channels": 32,
                "n_hidden_channels": 64,
	        "dropout": 0.0,
                "l2_reg": 0,
                "learning_rate": 1e-4,
                "lr_sched": True,
                "lr_factor": 0.5,
                "lr_patience": 10,
                "lr_mode": 'max',
                "log_dir": None,
                "transfer": None,
                "n_rotations": 1,
                "balance_classes": False,
               "num_deep_layers": 28,
               "data_path": '../../data/ln_malignancy',
               "patch_dir": 'Extracted_Patches_All_Pt',
               "edge_file": 'proto_graphs_061324.pkl',
               "patient_feature_file": 'features_and_labels_061324.pkl',
               "data_version": 'v1',
               }         

